### ISSUE TITLE
I want the split polygon to share this split line instead of gaps. Is there an option to control whether to share

### ISSUE THREAD

**Issue by LuckDogHu** [ReyhaneMasumi/mapbox-gl-draw-split-polygon-mode#8]
![image](https://user-images.githubusercontent.com/45897157/201820532-a0e949f0-f619-4ded-9818-274253b3b928.png)

**Comment by mhsattarian** [comment]
options to control the thickness of the splitting `lineString` are added now:

```js
draw.changeMode(
  "split_polygon",
  /** Default option vlaues: */
  {
    highlightColor: "#222",
    lineWidth: 0.001,
    lineWidthUnit: "kilometers",
  }
);
```

> these `lineWidth* options are passed to [`lineOffset` method](lineOffset) from `Turf.js`.
